version: "3.8"

services:
  backend:
    build:
      context: .
    ports:
      - "3001:3001"
    environment:
      - DB_HOST=postgres
      - DB_USER=postgres
      - DB_PASSWORD=01022546zazakoeiei
      - DB_NAME=gomedDB
      - DB_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy  # ✅ เพิ่มเงื่อนไขให้ backend รอ database พร้อมใช้งาน

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 01022546zazakoeiei
      POSTGRES_DB: gomedDB
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:   # ✅ เพิ่ม healthcheck ให้ database
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "8080:80"

volumes:
  postgres_data:
